### ISSUE TITLE
Checklist MVV

### ISSUE THREAD

**Issue by thlmenezes** [TMTecnologia/endividometro#1]
## Padrões de Projeto

- [x] Configuração ESLint
- [x] Configuração de Padrões de Commits (Commitlint + Commitzen + cz-git)
  - https://github.com/thlmenezes/boladao-t3/blob/main/commitlint.config.js
- [x] CI - Validação de Commits [commitlint.yml](https://github.com/thlmenezes/boladao-t3/tree/main/.github/workflows)
- [x] CI - Análise estática do código [reviewdog.yml](https://github.com/thlmenezes/boladao-t3/tree/main/.github/workflows)
- [x] CI - Format Package Json [syncpack](https://www.npmjs.com/package/syncpack)
- [x] CI - Check Dependencies for Vulnerabilities [audit.yml](https://github.com/TMTecnologia/turborepo-tmtecnologia/blob/main/.github/workflows/audit.yml)
- [x] ESLint ordenação automática das classes do tailwindCSS
- [ ] #2

## MVV

- [x] create t3 app
- [x] daisyUI temas cmyk e business
- [x] Login com Google
- [ ] CRUD dívida + Visualização Mensal
- [ ] Integração Clockify
- [ ] CRUD quadro
- [ ] Compartilhar quadro com outro usuário
- [ ] Somente o criador do quadro pode alterá-lo ou excluí-lo

## Versão 2

- [ ] Criar LandingPage com funcionalidades planejadas e fotos
- [ ] CRUD guilda
  - Uma guilda tem vários quadros e vários integrantes e um único dono
- [ ] Visualizar no Calendário

## Versão 3

- [ ] Visualização Anual e Gráficos
- [ ] Integração Calendário Google
- [ ] Metas Financeiras
- [ ] Categorias

**Comment by thlmenezes** [comment]
## Listar dívidas do mês

![lista de dívidas de outubro](https://user-images.githubusercontent.com/33532177/197672064-eede9935-211c-4cb0-8d4f-ed2887397977.png)

## Cadastrar dívida

![Criar dívida](https://user-images.githubusercontent.com/33532177/197672395-347b1ff6-729a-4634-8ede-2df921caa189.png)

## Visualizar no calendário

![visualização no calendário das dívidas do mês](https://user-images.githubusercontent.com/33532177/197672740-674fceee-e597-453a-a3e7-8bebc7e13880.png)

## Página Inicial

![página inicial do endividômetro](https://user-images.githubusercontent.com/33532177/197671915-34862d0a-a134-4826-a6eb-4acffac2e7bf.png)

## Visualização anual com gráficos

![visualização do ano de 2022](https://user-images.githubusercontent.com/33532177/197672248-dc18e235-0c7a-4691-890c-821d9c19e52b.png)

## Anotações sobre API do clockify

![argumentos para API do clockify](https://user-images.githubusercontent.com/33532177/197672601-bbe07e26-5918-416a-8eff-b392332e421c.png)

**Comment by Carvalhojj** [comment]
Library baseada em react e tailwindcss para facilitar a criação de dashboards: https://www.tremor.so/

**Comment by thlmenezes** [comment]
> Library baseada em react e tailwindcss para facilitar a criação de dashboards: https://www.tremor.so/

Experimentei hoje na live, foi uma excelente experiência para apresentar os dados, contudo bem limitante na estilização; tentei trocar a cor de um texto e não rolou.

Avaliando a possibilidade de usar o HTML puro mesmo OU [React Aria - useTable](https://react-spectrum.adobe.com/react-aria/useTable.html) OU [React Table](https://react-table-v7.tanstack.com/)
